spring:
  datasource:
    url: jdbc:mysql://localhost:3380/lollipop_cardbase?serverTimezone=UTC&useSSL=false
    username: root
    password: cinnamon
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect